SELECT * FROM hr.employees;

SELECT first_name,last_name,phone_number FROM hr.employees;

SELECT first_name FROM hr.employees WHERE first_name="Steven";

SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM hr.employees GROUP BY JOB_ID;

SELECT MANAGER_ID, SALARY FROM hr.employees WHERE SALARY = (SELECT min(SALARY) FROM employees);

SELECT DEPARTMENT_ID, SUM(SALARY) FROM hr.employees GROUP BY DEPARTMENT_ID;

SELECT JOB_ID, AVG(SALARY) FROM hr.employees WHERE JOB_ID NOT LIKE 'IT_PROG' GROUP BY JOB_ID;

SELECT JOB_ID, MAX(SALARY) FROM hr.employees GROUP BY JOB_ID HAVING MAX(SALARY) >= 10000;

SELECT DEPARTMENT_NAME, locations.LOCATION_ID, STREET_ADDRESS, CITY, STATE_PROVINCE, COUNTRY_NAME FROM hr.departments NATURAL JOIN hr.locations NATURAL JOIN hr.countries;

SELECT FIRST_NAME, LAST_NAME, employees.DEPARTMENT_ID, DEPARTMENT_NAME FROM employees
INNER JOIN departments ON employees.DEPARTMENT_ID = departments.DEPARTMENT_ID;

SELECT FIRST_NAME, LAST_NAME, JOB_TITLE, employees.DEPARTMENT_ID, DEPARTMENT_NAME FROM employees
INNER JOIN jobs ON employees.JOB_ID = jobs.JOB_ID
INNER JOIN departments ON employees.DEPARTMENT_ID = departments.DEPARTMENT_ID
INNER JOIN locations ON departments.LOCATION_ID = locations.LOCATION_ID
WHERE CITY = 'LONDON';

SELECT DEPARTMENT_NAME, COUNT(EMPLOYEE_ID) FROM departments
INNER JOIN employees ON departments.DEPARTMENT_ID = employees.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE FROM employees WHERE HIRE_DATE > (SELECT HIRE_DATE FROM employees WHERE LAST_NAME = 'Jones');

SELECT DEPARTMENT_ID, AVG(SALARY) FROM employees GROUP BY DEPARTMENT_ID HAVING COUNT(DEPARTMENT_ID) > 10;

SELECT EMPLOYEE_ID, REVERSE(SUBSTR(REVERSE(EMAIL), 4)) FROM employees;

SELECT STREET_ADDRESS FROM locations WHERE LENGTH(STREET_ADDRESS) = 40;

SELECT FIRST_NAME AS FirstName, LENGTH(FIRST_NAME) AS Length FROM employees 
WHERE FIRST_NAME LIKE 'A%' OR FIRST_NAME LIKE 'J%' OR FIRST_NAME LIKE 'M%'
ORDER BY FIRST_NAME;

select * from employees where first_name="Adam" or first_name="Jean";